version: '2' 
services:
  nesp2_website:
    restart: unless-stopped
    build:
      args:
        POSTGRES_url: ${POSTGRES_URL}
        POSTGRES_user: ${POSTGRES_USER}
        POSTGRES_pw: ${POSTGRES_PW}
        POSTGRES_db: ${POSTGRES_DB}
      context: .
    image: nesp2_website
    container_name: nesp2_website
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 index:app --workers=5
 
  nginx:
    restart: unless-stopped
    build: ./nginx
    ports:
      - 80:80
